# PRACTICE PROBLEMS ON STRING & LIST


**<font color='red'>[MUST MAINTAIN VARIABLE NAMING CONVENTIONS FOR ALL THE TASKS]</font>**
**<font color='red'>[Solve all the tasks sequentially]</font>**


### Task 1
Write a python program that will take a number as an input and check whether the number is Awesome or not. If the number is Awesome, it prints True. Otherwise False.

**Awesome number**: a number where every digit is less than its immediate left digit is called an Awesome number. A single-digit number cannot be an awesome number(e.g. 5421 is an Awesome number.)

==========================================================

**Sample Input1:**\
976321\
**Sample Output1:**\
True

==========================================================

**Sample Input2:**\
9766321\
**Sample Output2:**\
False

==========================================================

**Sample Input3:**\
9\
**Sample Output3:**\
False

==========================================================

**Sample Input4:**\
78\
**Sample Output4:**\
False

==========================================================

**Sample Input5:**\
87\
**Sample Output4:**\
True


In [1]:
given = int(input())
given = [int(x) for x in str(given)]
new = []
right = given[0]+1

for i in range(len(given)):
    if right > given[i]:
        new.append(given[i])
        right = given[i]

if len(given) == 1:
    print(False)
elif len(given) == len(new):
    print(True)
else:
    print(False)

9786421
False


In [3]:
def check_awesome(n: str) -> bool:
    """
    This will take string and return boolean value
    """
    if len(n) == 1: return False
    for i in range(len(n)-1):
        if n[i] > n[i+1]:
            continue
        else:
            return False
    
    
    return True


print(check_awesome("976321"))
print(check_awesome("9766321"))
print(check_awesome("9"))
print(check_awesome("78"))
print(check_awesome("87"))

print(check_awesome.__doc__)

True
False
False
False
True

    This will take string and return boolean value
    


### Task 2

Write a python program that will take a number in a list of numbers(integer) as an input from the user and print whether the number is Awesome or not. 

==========================================================

**Sample Input1:**\
[976321, 321, 9763221, 9742, 876, 3211]\
**Sample Output1:**\
976321 is an awesome number.\
321 is an awesome number.\
9763221 is a not-so-awesome number.\
9742 is an awesome number.\
876 is an awesome number.\
3211 is a not-so-awesome number.

==========================================================

**Sample Input2:**\
[97821, 97210, 979210]\
**Sample Output2:**\
97821 is a not-so-awesome number.\
97210 is an awesome number.\
979210 is a not-so-awesome number.


In [21]:
#TODO
n=int(input('Enter how many number wil enter:'))
list1=[]
for i in range(n):
    numb=int(input('Enter numbers:'))
    list1.append(numb)
new=[]
for j in list1:
    given = [int(x) for x in str(j)]
    right = given[0]+1

    for k in range(len(given)):
        if right > given[k]:
            new.append(given[k])
            right = given[k]
    value=j
    if len(given) == 1:
        print(value,'is a not-so-awesome number')
    elif len(given) == len(new):
        print(value,'is an awesome number')
    else:
        print(value,'is a not-so-awesome number')
    new=[]

Enter how many number wil enter:2
Enter numbers:97821
Enter numbers:97210
97821 is a not-so-awesome number
97210 is an awesome number


In [2]:
def check_awesome(n: str) -> bool:
    if len(n) == 1: return False
    for i in range(len(n)-1):
        if n[i] > n[i+1]: continue
        else: return False
    return True

def awesome_list(listo: list) -> print:
    for elem in listo:
        if check_awesome(str(elem)):
            print(f"{elem} is a awesome number.")
        else:
            print(f"{elem} is a not-so-awesome number.")




listo = eval("[976321, 321, 9763221, 9742, 876, 3211]")
awesome_list(listo)

976321 is a awesome number.
321 is a awesome number.
9763221 is a not-so-awesome number.
9742 is a awesome number.
876 is a awesome number.
3211 is a not-so-awesome number.


### Task 3


Write a python program that will take a string as input from the user where each number is separated by a comma. Then gets the numbers from the given string and removes all extra spaces. Stores the clean numbers in a list and prints it.

**Hints:** For obtaining the numbers from the string, use split(). For cleaning the data, use strip().

==========================================================

**Sample Input1:**\
"97821, 1 &nbsp;&nbsp;&nbsp;  , 97210,&nbsp;&nbsp; 963, &nbsp;&nbsp;&nbsp;979210 , 979210 "\
**Sample Output1:**\
Data after cleaning: [97821, 1, 97210, 963, 979210, 979210]

==========================================================

**Sample Input2:**\
"976321, 321&nbsp;&nbsp;,&nbsp;&nbsp;&nbsp;9763221, &nbsp;&nbsp;&nbsp;9742, 876,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3211"\
**Sample Output2:**\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211]

==========================================================

**Sample Input3:**\
"976321, 321 ,&nbsp;&nbsp;&nbsp; 9763221, 9742, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;876, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3211, 976321&nbsp;&nbsp;&nbsp;&nbsp;, 9742"\
**Sample Output3:**\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]


In [7]:
list1=input('Enter digits separated by comma:')
list2=list1.split(',')
list3=[]
for i in list2:
    list3.append(int(i))
print('Data after cleaning:',list3)

Enter digits separated by comma:976321, 321  ,   9763221,    9742, 876,        3211
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211]


In [1]:
def data_cleaner(string):
    return "Data after cleaning: ", [int(x) for x in string.split(',')]

print(*data_cleaner("97821, 1     , 97210,       963,       979210 , 979210 "))
print(*data_cleaner("976321, 321  ,   9763221,    9742, 876,        3211"))
print(*data_cleaner("976321, 321 ,    9763221, 9742,      876,       3211, 976321    , 9742"))

Data after cleaning:  [97821, 1, 97210, 963, 979210, 979210]
Data after cleaning:  [976321, 321, 9763221, 9742, 876, 3211]
Data after cleaning:  [976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]


### Task 4

Write a python program that will take a list of numbers(integer) as an input from the user and does the following.
* counts the number of valid, invalid, and duplicate numbers and prints these to the user.
* stores the valid and invalid numbers in a list format and prints these to the user. You need to make sure that a number is stored only Once. **Valid numbers:** A number with a minimum length of 4 and a maximum length of 6 is considered to be valid for this assignment.
* Calculate and print the percentage of valid numbers, invalid numbers, and duplicate numbers to the user. 


**Hints:** Use membership operator in and not in for checking the duplicates. For calculating the percentage, count the numbers of a particular number type.

==================================================


**Sample Input1:**\
[97821, 1, 97210, 963, 979210, 979210]\
**Sample Output1:**\
================================================\
Total numbers present in the given string: 6\
Valid number count: 3\
Valid numbers in list: [97821, 97210, 979210]\
Invalid number count: 2\
Invalid numbers in list: [1, 963]\
Duplicate number count: 1\
================================================\
Valid number percentage(%): 50.0\
Invalid number percentage(%): 33.333333333333336\
Duplicate number percentage(%): 16.666666666666668\
================================================\


**Sample Input2:**\
[976321, 321, 9763221, 9742, 876, 3211]\
**Sample Output2:**\
================================================\
Total numbers present in the given string: 6\
Valid number count: 3\
Valid numbers in list: [976321, 9742, 3211]\
Invalid number count: 3\
Invalid numbers in list: [321, 9763221, 876]\
Duplicate number count: 0\
================================================\
Valid number percentage(%): 50.0\
Invalid number percentage(%): 50.0\
Duplicate number percentage(%): 0.0\
================================================\

**Sample Input3:**\
[976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]\
**Sample Output3:**\
================================================\
Total numbers present in the given string: 8\
Valid number count: 3\
Valid numbers in list: [976321, 9742, 3211]\
Invalid number count: 3\
Invalid numbers in list: [321, 9763221, 876]\
Duplicate number count: 2\
================================================\
Valid number percentage(%): 37.5\
Invalid number percentage(%): 37.5\
Duplicate number percentage(%): 25.0\
================================================\


In [6]:
#TODO
list1=input('Enter digits using space:')
list2=list1.split(' ')
list3=[]
list4=[]
list5=[]
a=[]
for i in list2:
    if len(i)>=4 and len(i)<=6:
        list3.append(int(i))
    else:
        list4.append(int(i))
for j in list2:
    if j in a:
        continue
    else:
        a.append(j)
for k in list3:
    if k in list5:
        continue
    else:
        list5.append(k)
percentage=100/len(list2)
print('The total numbers present in the given string:',len(list2))
print('Valid number count:',len(list5))
print('Valid number in list:',list5)
print('Invalid number count:',len(list4))
print('Invalid number in list:',list4)
print('Duplicate number count:',len(list2)-len(a))
print('Valid number percentage(%):',percentage*len(list5))
print('Invalid number percentage(%):',percentage*len(list4))
print('Duplicate number percentage(%):',percentage*(len(list2)-len(a)))

Enter digits using space:97821 1 97210 963 979210 979210
The total numbers present in the given string: 6
Valid number count: 3
Valid number in list: [97821, 97210, 979210]
Invalid number count: 2
Invalid number in list: [1, 963]
Duplicate number count: 1
Valid number percentage(%): 50.0
Invalid number percentage(%): 33.333333333333336
Duplicate number percentage(%): 16.666666666666668


### Task 5

Write a python program that will take a list of numbers(integer) as an input from the user. Then stores the valid numbers, the sum of digits, and multiplication of the digits for each valid number in a list where each number is the 1st element of the list, the sum of digits is the 2nd element of the list and the multiplication of digits is the 3rd element of the list. Finally, print the nested list to the user. 

**Sample Input1:**\
[97821, 97210, 979210]\
**Sample Output1:**\
Data [number, sum of digits, product of digits]: [[97821, 27, 1008], [97210, 19, 0], [979210, 28, 0]]

================================================

**Sample Input2:**\
[976321, 9742, 3211, 30987]\
**Sample Output2:**\
Data [number, sum of digits, product of digits]: [[976321, 28, 2268], [9742, 22, 504], [3211, 7, 6], [30987, 27, 0]]

================================================

**Sample Input3:**\
[976321, 9640, 3211]\
**Sample Output3:**\
Data [number, sum of digits, product of digits]: [[976321, 28, 2268], [9640, 19, 0], [3211, 7, 6]]

================================================


In [2]:
list1=input('Enter digits using space:')
list2=list1.split(' ')
list3=[]
a=[]
sum=0
product=1
for i in list2:
    for j in range(len(i)):
        sum+=int(i[j])
        product*=int(i[j])
    b=[int(i),sum,product]
    a.append(b)
    sum=0
    product=1
list3.extend(a)
print('Data[number,sum of digits,product of digits]:',list3)

Enter digits using space:976321 9742 3211 30987
Data[number,sum of digits,product of digits]: [[976321, 28, 2268], [9742, 22, 504], [3211, 7, 6], [30987, 27, 0]]


In [4]:
def num_sum_pro(dhore_nilam_input_dilo):
    num_sum_pro_list = []
    for elem in dhore_nilam_input_dilo:
        digit = int(elem)
        summation = sum(map(int, str(elem)))
        product = 1
        for i in str(elem): product *= int(i)


        num_sum_pro_list.append([digit, summation, product])

    return num_sum_pro_list


dhore_nilam_input_dilo = eval("[97821, 97210, 979210]")
print(num_sum_pro(dhore_nilam_input_dilo))

[[97821, 27, 1008], [97210, 19, 0], [979210, 28, 0]]


### Task 6 (Merger of Task1-Task5)

Write a python program that will take a string as input from the user where each number is separated by a comma. The numbers must have a minimum length of 4 and a maximum length of 6 to be considered valid for this assignment. Then, you need to complete the following. 

* Part1: get the numbers from the given string, remove all extra spaces. (clean the data). Print the clean data to the user.
* Part2:count the number of valid, invalid, and duplicate numbers and print these to the user.
* Part3: store the valid and invalid numbers in a list format and print these to the user. You need to make sure that a number is stored only Once.
* Part4: Calculate and print the percentage of valid numbers, invalid numbers, and duplicate numbers to the user.
* Part5:store the valid numbers, the sum of digits, and multiplication of the digits for each valid number in a list where each number is the 1st element of the list, the sum of digits is the 2nd element of the list and the multiplication of digits is the 3rd element of the list. Finally, print the nested list to the user. 
* Part6: Check whether the valid numbers are Awesome or not. **Awesome number:** a number where every digit is less than its immediate left digit is called is an awesome number. (e.g. 5421 is an awesome number).

==============================================================================================

**Sample Input1:**\
"97821, 1 &nbsp;&nbsp;&nbsp;  , 97210,&nbsp;&nbsp; 963, &nbsp;&nbsp;&nbsp;979210 , 979210 "\
**Sample Output1:**\
Data after cleaning: [97821, 1, 97210, 963, 979210, 979210]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
================================================\
Total numbers present in the given string: 6\
Valid number count: 3\
Valid numbers in list: [97821, 97210, 979210]\
Invalid number count: 2\
Invalid numbers in list: [1, 963]\
Duplicate number count: 1\
================================================\
Valid number percentage(%): 50.0\
Invalid number percentage(%): 33.333333333333336\
Duplicate number percentage(%): 16.666666666666668\
================================================\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data of valid numbers:\
[number, sum of digits, product of digits]:\
[[976321, 28, 2268], [9640, 19, 0], [3211, 7, 6]]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
^_^ Awesomeness checking of the Valid numbers ^_^\
976321 is an awesome number.\
9640 is an awesome number.\
3211 is a not-so-awesome number.\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

==============================================================================================


**Sample Input2:**\
"976321, 321&nbsp;&nbsp;,&nbsp;&nbsp;&nbsp;9763221, &nbsp;&nbsp;&nbsp;9742, 876,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3211"\
**Sample Output2:**\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
================================================\
Total numbers present in the given string: 6\
Valid number count: 3\
Valid numbers in list: [976321, 9742, 3211]\
Invalid number count: 3\
Invalid numbers in list: [321, 9763221, 876]\
Duplicate number count: 0\
================================================\
Valid number percentage(%): 50.0\
Invalid number percentage(%): 50.0\
Duplicate number percentage(%): 0.0\
================================================\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data of valid numbers:\
[number, sum of digits, product of digits]:\
[[976321, 28, 2268], [9640, 19, 0], [3211, 7, 6]]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
^_^ Awesomeness checking of the Valid numbers ^_^\
976321 is an awesome number.\
9640 is an awesome number.\
3211 is a not-so-awesome number.\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX


==============================================================================================

**Sample Input3:**\
"976321, 321 ,&nbsp;&nbsp;&nbsp; 9763221, 9742, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;876, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3211, 976321&nbsp;&nbsp;&nbsp;&nbsp;, 9742"\
**Sample Output3:**\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
================================================\
Total numbers present in the given string: 8\
Valid number count: 3\
Valid numbers in list: [976321, 9742, 3211]\
Invalid number count: 3\
Invalid numbers in list: [321, 9763221, 876]\
Duplicate number count: 2\
================================================\
Valid number percentage(%): 37.5\
Invalid number percentage(%): 37.5\
Duplicate number percentage(%): 25.0\
================================================\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data of valid numbers:\
[number, sum of digits, product of digits]:\
[[976321, 28, 2268], [9640, 19, 0], [3211, 7, 6]]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
^_^ Awesomeness checking of the Valid numbers ^_^\
976321 is an awesome number.\
9640 is an awesome number.\
3211 is a not-so-awesome number.\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

In [ ]:
#TODO
list1=input('Enter digits separated by comma:')
list2=list1.split(',')
list31=[]
list3=[]
list4=[]
list5=[]
a=[]
for m in list2:
    list31.append(int(m))
    
for j in list2:
    if j in a:
        continue
    else:
        a.append(j)
        
for i in a:
    if len(i)>=4 and len(i)<=6:
        list3.append(int(i))
    else:
        list4.append(int(i))


        
list55=[]
for t in list5:
    list55.append(str(t))
        
lista=[]
aa=[]
sum=0
product=1
for q in list55:
    for w in range(len(q)):
        sum+=int(q[w])
        product*=int(q[w])
    b=[int(q),sum,product]
    aa.append(b)
    sum=0
    product=1
lista.extend(aa)
percentage=100/len(list2)



print('Data after clearing:',list31)
print('Data[number,sum of digits,product of digits]:',lista)

print('The total numbers present in the given string:',len(list2))
print('Valid number count:',len(list3))
print('Invalid number count:',len(list4))
print('Duplicate number count:',len(list2)-len(a))

print('Valid number in list:',list3)
print('Invalid number in list:',list4)

print('Valid number percentage(%):',percentage*len(list5))
print('Invalid number percentage(%):',percentage*len(list4))
print('Duplicate number percentage(%):',percentage*(len(list2)-len(a)))

print('Data[number,sum of digits,product of digits]:',lista)


new=[]
for o in list5:
    given = [int(x) for x in o]
    right = given[0]+1

    for p in range(len(given)):
        if right > given[p]:
            new.append(given[p])
            right = given[p]
    value=o
    if len(given) == 1:
        print(value,'is a not-so-awesome number')
    elif len(given) == len(new):
        print(value,'is an awesome number')
    else:
        print(value,'is a not-so-awesome number')
    new=[]

In [5]:
def clean_data(line):
    cleaned = []
    for el in line.split(','):
        num = ''
        for i in el:
            if i.isdigit():
                num+=i
        cleaned.append(num)
    cleaned_data = [int(x) for x in cleaned]
    print(f"\nData after cleaning: {cleaned_data}")
    return cleaned
    
def group_data(cleaned):
    x = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    grouped_data = {}
    # Age duplicated ber korte hobe, thn, 
    # not duplicated er upor ei loop chalate hobe
    group_cleaned = []
    for el in cleaned:
        if el not in group_cleaned:
            group_cleaned.append(el)
        

    for el in group_cleaned:
        lenel = len(el)
        keys = grouped_data.keys()
        if lenel >= 4 and lenel <= 6:
            if 'valid' not in keys:
                grouped_data['valid'] = [int(el)]
            else:
                grouped_data['valid'].append(int(el))
        if lenel < 4 or lenel > 6:
            if 'invalid' not in keys:
                grouped_data['invalid'] = [int(el)]
            else:
                grouped_data['invalid'].append(int(el))

        if cleaned.count(el) > 1:
            if 'duplicate' not in keys:
                grouped_data['duplicate'] = [int(el)]
            else:
                grouped_data['duplicate'].append(int(el))
    print(f"\n{x}\n               Data dictionary printing inside the function\n{grouped_data}\n{x}\n")
    return grouped_data
        
def digit_breaker(number):
    digits = []
    
    while number != 0:
        digit = number % 10
        number = number // 10
        digits.append(digit)
    return digits

def check_awesomeness(number):
    digits = digit_breaker(number)
    awesome = False
    if len(digits) > 0:
        for i in range(len(digits)-1, 0, -1):
            if digits[i] < digits[i-1] or digits[i] == digits[i-1]:
                awesome = False
                break
            else:
                awesome =  True
    return awesome

def check_awesome(listo):
    def check_awesomeness(number):
        digits = digit_breaker(number)
        awesome = False
        if len(digits) > 0:
            for i in range(len(digits)-1, 0, -1):
                if digits[i] < digits[i-1] or digits[i] == digits[i-1]:
                    awesome = False
                    break
                else:
                    awesome =  True
        return awesome
    awesome_list = ''
    for num in listo:
        if check_awesomeness(num):
            awesome_list+= f"{num} is an awesome number.\n"
        else:
            awesome_list+= f"{num} is a not-so-awesome number.\n"

    return awesome_list
def find_max_min(listo):
    listo = sorted(listo)
    max = listo[-1]
    min = listo[0]
    return max, min

def individual_line_data(line):
    x = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    # Clean the data and print it
    cleaned_data = clean_data(line)

    # Group with valid, invalid and duplicate
    grouped_data = group_data(cleaned_data)

    # Check if the valid number is awesome or not
    check_awesomeness = check_awesome(grouped_data.get('valid'))
    # print the maximum and minimum from the valid numbers 
    max_min = find_max_min(grouped_data.get('valid'))

    # Sob gulo return packet kore korlei hobe
    return cleaned_data, grouped_data, check_awesomeness, max_min
    

    



# individual_line_data("97821, 1 &nbsp;&nbsp;&nbsp;  , 97210,&nbsp;&nbsp; 963, &nbsp;&nbsp;&nbsp;979210 , 979210   ")
# individual_line_data("976321, 321&nbsp;&nbsp;,&nbsp;&nbsp;&nbsp;9763221, &nbsp;&nbsp;&nbsp;9742, 876,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3211")

def number_analysis(data):
    data = individual_line_data(data)

    print(f"""Returned Dictionary: {data[1]}
Valid number list obtained from dictionary: {data[1]['valid']}\n
^_^ Awesomeness checking of the Valid numbers ^_^\n{data[2]}
# Returned value of find_max_min: {data[-1]}
Valid number with maximum value is {data[-1][0]}
Valid number with minimum value is {data[-1][-1]}
""")

number_analysis("976321, 321 ,&nbsp;&nbsp;&nbsp; 9763221, 9742, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;876, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3211, 976321&nbsp;&nbsp;&nbsp;&nbsp;, 9742")


Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
               Data dictionary printing inside the function
{'valid': [976321, 9742, 3211], 'duplicate': [976321, 9742], 'invalid': [321, 9763221, 876]}
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Returned Dictionary: {'valid': [976321, 9742, 3211], 'duplicate': [976321, 9742], 'invalid': [321, 9763221, 876]}
Valid number list obtained from dictionary: [976321, 9742, 3211]

^_^ Awesomeness checking of the Valid numbers ^_^
976321 is an awesome number.
9742 is an awesome number.
3211 is a not-so-awesome number.

# Returned value of find_max_min: (976321, 3211)
Valid number with maximum value is 976321
Valid number with minimum value is 3211



Task 23
Write a python program that will convert a decimel number into a bynary number.

In [6]:
numb=int(input('Enter a decimel number:'))
a_list=[]

while numb>0:
    reminder=numb%2
    numb=numb//2
    a_list.append(reminder)
b_list=a_list[-1::-1]
for i in b_list:
    print(i,end='')

Enter a decimel number:10
1010

In [13]:
numb=int(input('Enter a decimel number:'))
a_list=[]

while numb>0:
    reminder=numb%2
    numb=numb//2
    a_list.append(reminder)

for count in range(len(a_list)-1,-1,-1):#or can use range(-1,-len(a_list),-1)
    print(a_list[count],end='')

Enter a decimel number:10
1010

Write a python programme that gives code like below but Limitation is 'H'.
Input:
ABCDEFGHIJKL
Output:
65B67D69F71H

In [17]:
word=input('Enter a string:')
for count in range(0,len(word)):
    if word[count]=='I':
        break
    if count%2==0:
        numb=ord(word[count])
        print(numb, end='')
    else:
        print(word[count], end='')    
print()

Enter a string:ABCDEFGHIJKL
65B67D69F71H


Write a python code that bring out the char only from any string and tell how many char is there.
Input:
65B67D69F71H
Output:
BDFH

In [19]:
word=input('Enter a string:')
a_string=''
count=0
for letter in word:
    if ord(letter) in range(65,91):
        a_string=a_string+letter
        count=count+1
print('The final output is:',a_string)
#print('There are total',count,'char')
print('There are total {} char'.format(count))

Enter a string:65B67D69F71H
The final output is: BDFH
There are total 4 char
