# PRACTICE PROBLEMS ON FUNCTION


**<font color='red'>[MUST MAINTAIN VARIABLE NAMING CONVENTIONS FOR ALL THE TASKS]</font>**
**<font color='red'>[Solve all the tasks sequentially]</font>**


### Task 1
Write a function called **check_awesomeness** that takes a number as an argument and Checks whether the number is Awesome or not. If the number is Awesome, it returns True. Otherwise False.
 
**Awesome number:** a number where every digit is less than its immediate left digit is called an Awesome number. A single digit number cannot be a awesome number(e.g. 5421 is an Awesome number).

==========================================================

**Function Call1:**\
check_awesomeness(976321)\
**Output1:**\
True

==========================================================

**Function Call2:**\
check_awesomeness(9766321)\
**Output2:**\
False

==========================================================

**Function Call3:**\
check_awesomeness(9)\
**Output3:**\
False

==========================================================

**Function Call4:**\
check_awesomeness(78)\
**Output4:**\
False

==========================================================

**Function Call5:**\
check_awesomeness(87)\
**Output4:**\
True

In [7]:
def check_awesomeness(given):
    given = [int(x) for x in str(given)]
    new = []
    right = given[0]+1

    for i in range(len(given)):
        if right > given[i]:
            new.append(given[i])
            right = given[i]

    if len(given) == 1:
        output=False
    elif len(given) == len(new):
        output=True
    else:
        output=False
    
    return output
check_awesomeness(int(input()))

54321


True

### Task 2
Write a function called **check_awesome** that takes a list of numbers(integer) as an argument and Prints whether the number is Awesome or not.

**<font color='red'>Must reuse the check_awesomeness() function.</font>**

==========================================================

**Function Call1:**\
check_awesome([976321, 321, 9763221, 9742, 876, 3211])\
**Output1:**\
976321 is an awesome number.\
321 is a awesome number.\
9763221 is a not-so-awesome number.\
9742 is an awesome number.\
876 is an awesome number.\
3211 is a not-so-awesome number.

==========================================================

**Function Call2:**\
check_awesome([97821, 97210, 979210])\
**Output2:**\
97821 is a not-so-awesome number.\
97210 is an awesome number.\
979210 is a not-so-awesome number.

In [5]:
def check_awesomeness(given):
    given = [int(x) for x in str(given)]
    new = []
    right = given[0]+1

    for i in range(len(given)):
        if right > given[i]:
            new.append(given[i])
            right = given[i]

    if len(given) == 1:
        output=False
    elif len(given) == len(new):
        output=True
    else:
        output=False
    
    return output

def check_awesome(list1):
    for i in list1:
        a=check_awesomeness(i)
        if a==True:
            print('{} is an awesome number'.format(i))
        else:
            print('{} is not-so-awesome number'.format(i))
    
    return
check_awesome(list1=[int(x) for x in input('Enter numbers using comma:').split(',')])

Enter numbers using comma:976321,321,9763221,9742,876,3211
976321 is an awesome number
321 is an awesome number
9763221 is not-so-awesome number
9742 is an awesome number
876 is an awesome number
3211 is not-so-awesome number


### Task 3
Write a function called **find_max_min** that takes a list of numbers(integers) as a  function parameter and finds the numbers with maximum and minimum value. Then returns these two numbers as a **tuple** and prints the results using tuple unpacking in the function call accorrding to the given format. Both valid and invalid numbers should be considered for finding maximum and minimum.<font color='red'>[Must use tuple packing & unpacking] </font> 

==========================================================

**Function Call1:**\
find_max_min([976321, 321, 9763221, 9742, 876, 3211, 976321, 9742])\
**Output1:**\
Returned value from find_max_min() is: (9763221, 321)\
Number with maximum value is 9763221\
Number with minimum value is 321

==========================================================

**Function Call2:**\
find_max_min([97821, 1, 97210, 963, 979210, 979210])\
**Output2:**\
Returned value from find_max_min() is: (979210, 1)\
Number with maximum value is 979210\
Number with minimum value is 1

In [22]:
def find_max_min(list1):
    list2=[x for x in list1.split(',')]
    sum1=[]
    dic1={}
    final_list=[]
    for i in list2:
        total=0
        for j in range(len(i)):
            total+=int(i[j])
        sum1.append(total)
        dic1[total]=i
        
    max1=-9999999999    
    for char1 in sum1:
        if char1>max1:
            max1=char1
            
    min1=9999999999        
    for char2 in sum1:
        if char2<min1:
            min1=char2
    
    tup_lst=[max1,min1]
    for k in tup_lst:
        if k in dic1:
            final_list.append(int(dic1[k]))
            
    tup1=tuple(final_list)
    
    return tup1

my_tuple=find_max_min(list1=input('Enter numbers using comma:'))
print('Returned value from find_max_min() is:',my_tuple)
a,b=my_tuple
print('Number with maximum value is',a)
print('Number with minimum value is',b)

Enter numbers using comma:976321,321,9763221,9742,876,3211,976321,9742
Returned value from find_max_min() is: (9763221, 321)
Number with maximum value is 9763221
Number with minimum value is 321


### Task 4
Write a function called **data_cleaning** that takes a string as an argument. Then gets the numbers from the given string and removes all extra spaces. Stores the clean numbers (integers) in a list and **returns** it to the function call.

==========================================================

**Function Call1:**\
data_cleaning("97821, 1 &nbsp;&nbsp;&nbsp;  , 97210,&nbsp;&nbsp; 963, &nbsp;&nbsp;&nbsp;979210 , 979210   ")\
**Output1:**\
Data after cleaning: [97821, 1, 97210, 963, 979210, 979210]

==========================================================

**Function Call2:**\
data_cleaning("976321, 321&nbsp;&nbsp;,&nbsp;&nbsp;&nbsp;9763221, &nbsp;&nbsp;&nbsp;9742, 876,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3211")\
**Output2:**\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211]

==========================================================

**Function Call3:**\
data_cleaning("976321, 321 ,&nbsp;&nbsp;&nbsp; 9763221, 9742, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;876, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3211, 976321&nbsp;&nbsp;&nbsp;&nbsp;, 9742")\
**Output3:**\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]

In [29]:
def data_cleaning(str1):
    list1=str1.split(',')
    clean_lst=[]
    for i in list1:
        str2=i.strip()
        int1=int(str2)
        clean_lst.append(int1)
    return clean_lst
data_cleaning(input('Enter values using space:'))

Enter values using space:976321, 321 ,    9763221, 9742,      876,       3211, 976321    , 9742


[976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]

### Task 5
Write a function called **grouping_data** that takes  a list of numbers(integers) as a  function parameter and creates a dictionary where "valid", "invalid", and "duplicate" are the keys. The numbers that falls in those categories are the values.

**Valid & Invalid numbers:** A number with a minimum length of 4 and a maximum length of 6 is considered to be valid for this assignment. All the other numbers are considered to be Invalid numbers.\
**Duplicate numbers:** If a number appears more than once in the string, then that is a dupliacte number. Both valid and invalid numbers can be duplicates.

Lastly, print the dictionary **inside the function** and **return** the dictionary to the function call.

==========================================================

**Function Call1:**\
grouping_data([97821, 1, 97210, 963, 979210, 979210])\
**Output1:**\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [97821, 97210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [97821, 97210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}\
Valid number list obtained from the dictionary: [97821, 97210, 979210]


==========================================================

**Function Call2:**\
grouping_data([976321, 321, 9763221, 9742, 876, 3211])\
**Output2:**\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': []}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': []}\
Valid number list obtained from the dictionary: [976321, 9742, 3211]


==========================================================

**Function Call3:**\
grouping_data([976321, 321, 9763221, 9742, 876, 3211, 976321, 9742])\
**Output3:**\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}\
Valid number list obtained from the dictionary: [976321, 9742, 3211]



In [36]:
def grouping_data(list1):
    clean_lst=[]
    duplicate=[]
    valid=[]
    invalid=[]
    for i in list1:
        if i not in clean_lst:
            clean_lst.append(i)
        else:
            duplicate.append(i)
            
    for j in clean_lst:
        str2=str(j)
        if len(str2)>=4 and len(str2)<=6:
            valid.append(j)
        else:
            invalid.append(j)
            
    dic1={'valid':valid,'invalid':invalid,'dulicate':duplicate}
    
    return dic1
list1=[int(x) for x in input().split(',')]
grouping_data(list1)

976321, 321, 9763221, 9742, 876, 3211, 976321, 9742


{'valid': [976321, 9742, 3211],
 'invalid': [321, 9763221, 876],
 'dulicate': [976321, 9742]}

### Task6
Write a function called **individual_line_data** that takes a string as an argument. This function should do the following. 
* clean and prints the data.
* group the numbers in a dictionary obtained from the given string.
* check whether the **valid numbers** are awesome or not.
* find and print the maximum and minimum number among the **valid numbers** obtained from the given string.

*Hints:*\
You MUST reuse data_cleaning(), grouping_data(), check_awesome() and find_max_min() functions. 

==========================================================

**Function Call1:**\
individual_line_data("97821, 1 &nbsp;&nbsp;&nbsp;  , 97210,&nbsp;&nbsp; 963, &nbsp;&nbsp;&nbsp;979210 , 979210   ")\
**Output1:**\
Data after cleaning: [97821, 1, 97210, 963, 979210, 979210]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [97821, 97210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [97821, 97210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}\
Valid number list obtained from the dictionary: [97821, 97210, 979210]\
=================================================\
^_^ Awesomeness checking of the Valid numbers ^_^\
97821 is a not-so-awesome number.\
97210 is an awesome number.\
979210 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (979210, 97210)\
Valid number with maximum value is 979210\
Valid number with minimum value is 97210




**Function Call2:**\
individual_line_data("976321, 321&nbsp;&nbsp;,&nbsp;&nbsp;&nbsp;9763221, &nbsp;&nbsp;&nbsp;9742, 876,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3211")\
**Output2:**\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': []}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': []}\
Valid number list obtained from the dictionary: [976321, 9742, 3211]\
=================================================\
^_^ Awesomeness checking of the Valid numbers ^_^\
976321 is an awesome number.\
9742 is an awesome number.\
3211 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (976321, 3211)\
Valid number with maximum value is 976321\
Valid number with minimum value is 3211



**Function Call3:**\
individual_line_data("976321, 321 ,&nbsp;&nbsp;&nbsp; 9763221, 9742, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;876, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3211, 976321&nbsp;&nbsp;&nbsp;&nbsp;, 9742")\
**Output3:**\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}\
Valid number list obtained from the dictionary: [976321, 9742, 3211]\
=================================================\
^_^ Awesomeness checking of the Valid numbers ^_^\
976321 is an awesome number.\
9742 is an awesome number.\
3211 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (976321, 3211)\
Valid number with maximum value is 976321\
Valid number with minimum value is 3211


In [52]:
def individual_line_data(input1):
    def data_cleaning(str1):
        list1=str1.split(',')
        clean_lst=[]
        for i in list1:
            str2=i.strip()
            int1=int(str2)
            clean_lst.append(int1)
        return clean_lst

    def grouping_data(list1):
        clean_lst=[]
        duplicate=[]
        valid=[]
        invalid=[]
        for i in list1:
            if i not in clean_lst:
                clean_lst.append(i)
            else:
                duplicate.append(i)

        for j in clean_lst:
            str2=str(j)
            if len(str2)>=4 and len(str2)<=6:
                valid.append(j)
            else:
                invalid.append(j)

        dic1={'valid':valid,'invalid':invalid,'dulicate':duplicate}

        return dic1

    def check_awesomeness(given):
        given = [int(x) for x in str(given)]
        new = []
        right = given[0]+1

        for i in range(len(given)):
            if right > given[i]:
                new.append(given[i])
                right = given[i]

        if len(given) == 1:
            output=False
        elif len(given) == len(new):
            output=True
        else:
            output=False

        return output

    def check_awesome(c):
        for i in c:
            a=check_awesomeness(i)
            if a==True:
                print('{} is an awesome number'.format(i))
            else:
                print('{} is not-so-awesome number'.format(i))

        return

    def find_max_min(c):
        list2=c
        sum1=[]
        dic1={}
        final_list=[]
        for i in list2:
            total=0
            string=str(i)
            for j in range(len(string)):
                total+=int(string[j])
            sum1.append(total)
            dic1[total]=i

        max1=-9999999999    
        for char1 in sum1:
            if char1>max1:
                max1=char1

        min1=9999999999        
        for char2 in sum1:
            if char2<min1:
                min1=char2

        tup_lst=[max1,min1]
        for k in tup_lst:
            if k in dic1:
                final_list.append(int(dic1[k]))

        tup1=tuple(final_list)

        return tup1

    a=data_cleaning(input1)
    b=grouping_data(a)
    c=b['valid']

    e=find_max_min(c)


    print('Data after cleaning:',a)
    print()
    print('Data dictionary printing inside the function:',b)
    print()
    print('Returned dictionary:',b)
    print()
    print('Valid number list obtained from the dictionary:',c)
    print()
    print('Awesomeness checking of the Valid numbers')
    d=check_awesome(c)
    print()
    print('Returned value from find_max_min() is:',e)

    my_tuple=e
    a,b=my_tuple
    print('Valid number with maximum value is',a)
    print('Valid number with minimum value is',b)
    
    return
individual_line_data(input('Enter values using space:'))

Enter values using space:976321, 321 ,    9763221, 9742,      876,       3211, 976321    , 9742
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]

Data dictionary printing inside the function: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'dulicate': [976321, 9742]}

Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'dulicate': [976321, 9742]}

Valid number list obtained from the dictionary: [976321, 9742, 3211]

Awesomeness checking of the Valid numbers
976321 is an awesome number
9742 is an awesome number
3211 is not-so-awesome number

Returned value from find_max_min() is: (976321, 3211)
Valid number with maximum value is 976321
Valid number with minimum value is 3211


### Task 7
Write a function called **number_analysis** that takes a list of strings as an argument and 
analyse those strings. \
**<font color='red'>Must reuse the individual_line_data() function.</font>**

In [ ]:
#todo

### Task 8
Run the following block of code for seeing the final output of this Problem.

**Output:**
######### Printing data for line no: 01 #########\
Data after cleaning: [321, 976322]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976322], 'invalid': [321], 'duplicate': []}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976322], 'invalid': [321], 'duplicate': []}\
Valid number list obtained from the dictionary: [976322]\
=================================================\
^_^ Awesomeness checking of the Valid numbers ^_^\
976322 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (976322, 976322)\
Valid number with maximum value is 976322\
Valid number with minimum value is 976322

&emsp; 

######### Printing data for line no: 02 #########\
Data after cleaning: [97821, 1, 97210, 963, 979210, 979210]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [97821, 97210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [97821, 97210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}\
Valid number list obtained from the dictionary: [97821, 97210, 979210]\
=================================================\
^_^ Awesomeness checking of the Valid numbers ^_^\
97821 is a not-so-awesome number.\
97210 is an awesome number.\
979210 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (979210, 97210)\
Valid number with maximum value is 979210\
Valid number with minimum value is 97210

&emsp; 

######### Printing data for line no: 03 #########\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': []}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': []}\
Valid number list obtained from the dictionary: [976321, 9742, 3211]\
=================================================\
^_^ Awesomeness checking of the Valid numbers ^_^\
976321 is an awesome number.\
9742 is an awesome number.\
3211 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (976321, 3211)\
Valid number with maximum value is 976321\
Valid number with minimum value is 3211

&emsp;

######### Printing data for line no: 04 #########\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}\
Valid number list obtained from the dictionary: [976321, 9742, 3211]\
=================================================\
^_^ Awesomeness checking of the Valid numbers ^_^\
976321 is an awesome number.\
9742 is an awesome number.\
3211 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (976321, 3211)\
Valid number with maximum value is 976321\
Valid number with minimum value is 3211

In [ ]:
lines_of_data = [
    "321 ,   976322",
    "97821, 1 , 97210, 963, 979210 , 979210",
    "976321, 321 ,   9763221, 9742, 876, 3211",
    "976321, 321 ,   9763221, 9742, 876, 3211, 976321, 9742"
]

number_analysis(lines_of_data)

### Task1n
Write a function in Python that will take a string text as input from the user and
returns the list of unique characters concatenated with their ASCII value at the
front and back side.

===================


**Sample Input:**\
"pythonbook"

**Function Calling:**\
function_name("pythonbook")

**Sample Output:**\
['112p112', '121y121', '116t116', '104h104', '111o111', '110n110', '98b98',
'107k107']

In [8]:
def unique_characters(string):
    clean=[]
    final=[]
    for i in string:
        if i not in clean:
            clean.append(i)
    for j in clean:
        num=ord(j)
        str1=str(num)
        final.append(str1+j+str1)
    return final
print(unique_characters(input()))

pythonbook
['112p112', '121y121', '116t116', '104h104', '111o111', '110n110', '98b98', '107k107']


### Task2n
Write a function in Python that will take a string text as input from the user and
returns a dictionary having the unique characters as the keys and the list of their
both-way indexes(positive and negative index) as the values.

====================

**Sample Input:**\
"pythonbook"

**Function Calling:**\
function_name("pythonbook")

**Sample Output:**\
{'p': [0, -10], 'y': [1, -9], 't': [2, -8], 'h': [3, -7], 'o': [4, -6, 7, -3, 8, -2], 'n': [5, -5], 'b': [6, -4], 'k':
[9, -1]}

In [9]:
def indice_list(string):
    indic = {}
    lenxo = len(string)
    for i in range(lenxo):
        if string[i] not in indic: 
            indic[string[i]] = [i, -lenxo+i]
        else: 
            indic[string[i]] += [i, -lenxo+i]
    return indic

print(indice_list("pythonbook"))

{'p': [0, -10], 'y': [1, -9], 't': [2, -8], 'h': [3, -7], 'o': [4, -6, 7, -3, 8, -2], 'n': [5, -5], 'b': [6, -4], 'k': [9, -1]}


### Task3n
Write a function in Python that will take a space separated string text as input
from the user and returns a dictionary having the unique words as the keys and
their frequency in the given text as the values in a sorted order(ascending)
according to the frequencies.

======================

**Sample Input:**\
"go there come and go here and there go care"

**Function Calling:**\
function_name("go there come and go here and there go care")

**Sample Output:**\
{'come': 1, 'here': 1, 'care': 1, 'there': 2, 'and': 2, 'go': 3}

In [10]:
def function_name(string):
    lst=string.split(' ')
    clean=[]
    dic={}
    for i in lst:
        if i not in clean:
            clean.append(i)
    for j in clean:
        count=0
        for char in lst:
            if char==j:
                count+=1
        dic[j]=count
    return dic
print(function_name(input()))

go there come and go here and there go care
{'go': 3, 'there': 2, 'come': 1, 'and': 2, 'here': 1, 'care': 1}


### Task4n
Write a function in Python that will take a number string text as input from the
user and returns a dictionary having the unique numbers as the keys and the
tuple of being the number to be even, odd, prime and perfect as the values.


==========================

**Sample Input:**\
"2441396"

**Function Calling:**\
function_name("2441396")

**Sample Output:**\
{2: ('even', 'prime', 'not perfect'), 4: ('even', 'not prime', 'not perfect'), 1: ('odd', 'not
prime', 'not perfect'), 3: ('odd', 'prime', 'not perfect'), 9: ('odd', 'not prime', 'not
perfect'), 6: ('even', 'not prime', 'perfect')}

In [3]:
def even_odd(num):
    if num%2==0:
        print('even')
    else:
        print('odd')
        
    return


def prime_function(num):    
    if num > 1:
        for i in range(2, num//2+1):
            if (num % i) == 0:
                output='not prime'
                break
        else:
            output='prime'
    else:
        output='not prime'
    
    return output

def perfect_function(y):
    for i in range(1,y):
        if y%i==0:
            sum=sum+i
    if sum==y:
        print('perfect')
    else:
        print('not perfect')
        
    return

def main_function(string):
    dic={}
    for i in string:
        if int(i) not in dic:
            dic[int(i)]=(even_odd(int(i)),prime_function(int(i)),perfect_function(int(i)))
            
    return dic

print(main_function(input()))

2441396
even


UnboundLocalError: local variable 'sum' referenced before assignment

### Task5n
Write a function in Python that will take two matrices as input from the user in
two lists. Then return the summation matrix and print it in the function call. [A
matrix can only be added to another matrix if the two matrices have the same
dimension]\
**<font color='red'>[Avoid using built-in Functions].</font>**


===============================

**Sample Input:**\
matrix_A = [ [1,5] , [-4,3] ]\
matrix_B = [ [2,-1] , [4,-1] ]


**Function Calling:**\
function_name(matrix_A , matrix_B)

**Sample Output:**\
matrix_sum = [ [3,4] , [0,2] ]

**Explanation:**\
Inside matrix_A and matrix_B, each list is a row matrix. For example, In matrix_A,\
Row 1----->[1,5]\
        Row 2---->[-4,3]\
In matrix_B,Row 1--->[2,-1]\
        Row 2--->[4,-1]\
So in output,matrix_sum = [ [1+2 , 5 -1] \
           [-4+ 4, 4 -1] ]


### Task6n
Write a Python program that will take a number N and for the keys(1 to N) take
N number of lists-as the values of a dictionary, with N number of elements in
each list from the user. Here Key number refers to the row numbers. \
Call a Convert_to _diagonal function that takes the dictionary of a nondiagonal
square matrix. Inside this Function, call another function convert_to list, which
converts the dictionary into a list of lists and returns the list. Where each list
represents a row matrix. \
After that, convert the square non-diagonal matrix list into a diagonal matrix list.
Then print it in the function.**<font color='red'>[Avoid using built-in Functions].</font>**


=======================================


**Sample Input:**\
4

square_matrix_dict = {1 : [1,2,3,4] , 2 : [4,5,6,7] , 3 : [7,8,9,3] , 4:[9,1,2,3] }


**Function Calling:**\
convert_to _diagonal(square_matrix_dict)

**Sample Output:**\
Non Diagonal matrix: \
1 2 3 4 \
4 5 6 7 \
7 8 9 3 \
9 1 2 3 

Diagonal Matrix :\
1 0 0 0\
0 5 0 0\
0 0 9 0\
0 0 0 3


**Explanation:**\
[**Square Matrix:** A square matrix is a matrix with the same number of rows and
columns.\
And **Diagonal Matrix:** Any given square matrix where all the elements are zero
except for the elements that are present diagonally is called a diagonal matrix]


1.Take input from user and create **square_matrix_dict** dictionary and call
**convert_to _diagonal(square_matrix_dict)**\
2.Convert, square_matrix_dict = {1 : [1,2,3,4] , 2 : [4,5,6,7] , 3 : [7,8,9,3] , 4:[9,1,2,3] }
into a list , nonDiagonal_matrix_list = [ [1,2,3,4] , [4,5,6,7] , [7,8,9,3] , [9,1,2,3] ]
using convert_to _list Function\
3.Return the list in **convert_to _diagonal** Function and convert the
“nonDiagonal_matrix_list” into a “ diagonal_matrix_list”\
4.Print both non-diagonal and diagonal matrices like the output.

In [2]:
def feedback():
    try:
        f(x, 4)
    finally:
        print('Feedback 1')
    print('Feedback 2')
feedback()

Feedback 1


NameError: name 'f' is not defined

Assume on a planet called “Chocolatey”, 1 month = 20 days and 1 year = 240  
days = 12 months.  Write a function Days that takes 2 arguments: a start  
date and the last date. Then calculates the number of days between these  
two dates(inclusive) and returns it to the function call.\
Assume, the start and last date will be given in dd/mm/yyyy format.

================================

**Function Call1:**\
function_name("3/8/2018", "12/12/2020")

**Sample Output1:**\
570

================================

**Function Call2:**\
function_name("3/8/2020", "12/12/2020")

**Sample Output2:**\
90

================================

**Function Call3:**\
function_name("3/8/2018", "3/9/2020")

**Sample Output3:**\
501

================================

**Function Call4:**\
function_name("3/8/2018", "10/8/2020")

**Sample Output4:**\
488

In [2]:
def calculate_date(d1, d2):
    d1 = list(map(int, d1.split('/')))
    d2 = list(map(int, d2.split('/')))

    year = abs(d1[2] - d2[2]) * 240

    month = abs(d1[1] - d2[1]) * 20
    day = abs(d1[0]-d2[0])+1

    day = year + month + day
    
    return d1,d2, day

print(calculate_date('3/8/2018', '12/12/2020'))

([3, 8, 2018], [12, 12, 2020], 570)


Design Australia class and England class which inherit from Cricket class 
so that the following code provides the expected output.

**Note:**\
Wicket Bonus = #of wicket * 1000\
Century Bonus = #of century * 1000\
addPlayerWithWickets and addPlayerWithCenturies methods should work any 
number of parameters assuming that the parameter number will be an even 
number and greater than 1.

**class Cricket:**\
     total_player = 0

     def __init__(self, name, number):\
         self.name = name\
         self.number = number\

     def __str__(self):\
         s =  "Name: "+self.name+", World Cup: "+self.number\
         return s

# Write your codes here.
# Do not change the following lines of code.

s1 = Australia("Australia", "5")\
print("==============================")\
s1.addPlayerWithWickets("Starc", 4,  "Hazlewood", 3)\
print("==============================")\
print(s1)\
print("==============================")\
s2 = England("England", "1")\
print("==============================")\
s2.addPlayerWithCenturies("Root", 5, "Ali", 3, "Woakes", 3)\
print("==============================")\
print(s2)\
print("==============================")\
print("Total Players:", Cricket.total_player)\

**OUTPUT:**\
Australia has won world cups 5 time(s)

==============================

==============================

Name: Australia, World Cup: 5\
Total Player(s): 2\
Player Details:\
Name: Starc, Wicket Bonus: 4000$\
Name: Hazlewood, Wicket Bonus: 3000$

==============================

England has won world cups 1 time(s)

==============================

==============================
Name: England, World Cup: 1\
Total Player(s): 3\
Player Details:\
Name: Root, Century Bonus: 5000$\
Name: Ali, Century Bonus: 3000$\
Name: Woakes, Century Bonus: 3000$

==============================

Total Players: 5

Write a python function that takes a dictionary as an argument. In that 
dictionary,  the name of the students will be the key and a list of courses 
will be the value.\
Inside the function, you have to take a course name as input until the user 
gives 'STOP' in the input. Your task is to display the list of the students 
taken that course after each input.

================================================

**Given Dictionary:**\
given_dict = { 'Mike' : ['CSE110','ENG101','MAT110'],
  'Simon' : ['CSE111','PHY111','MAT110', 'CSE230'],
  'Shawn' : ['CSE110','ENG101','MAT120','CSE230'],
  'Alice' : ['CSE110','ENG091','MAT092']  }
  
================================================

**Function call1:**\
function_name(given_dict)

**Sample Input 1:**\
CSE110\
MAT110\
CSE260\
STOP

**Sample Output 1:**\
[ 'Mike', 'Shawn', 'Alice' ]
[ 'Mike', 'Simon']
[ ]

**Explanation 1:**\
Mike, Shawn, and Alice are doing CSE110.
Mike and Simon are doing MAT110.
No student is doing CSE260.

================================================

**Function call2:**\
function_name(given_dict)

**Sample Input 2:**\
CSE111\
MAT110\
STOP

**Sample Output 2:**\
[ 'Simon' ]
[ 'Mike', 'Simon']

**Explanation 2:**\
Simon is doing CSE111\
Mike and Simon are doing MAT110

In [10]:
def function(lst):
    given_dict = { 'Mike' : ['CSE110','ENG101','MAT110'], 'Simon' : ['CSE111','PHY111','MAT110', 'CSE230'], 'Shawn' : ['CSE110','ENG101','MAT120','CSE230'], 'Alice' : ['CSE110','ENG091','MAT092'] }
    
    final_lst=[]
    for j in lst:
        lst2=[]
        for key,value in given_dict.items():
            for i in range(len(value)):
                if j==value[i]:
                    lst2.append(key)
        final_lst.append(lst2)
        
    for char in final_lst:
        print(char,end='')
        
    return

lst=[]

while True:
    input1 = input()
    if input1 == 'STOP': break
    lst.append(input1) 
function(lst)

CSE111
MAT110
STOP
['Simon']['Mike', 'Simon']

Write a function that takes a list as an argument. The list will contain a 
mixture of integers and letters. Your function should return a modified 
list so that --\
If the number of integers is twice the number of letters, then the list 
should contain 2 integers followed by 1 letter consecutively.\
If the number of letters is 3 times the number of integers (the ratio is 
3:1), then the list should contain 3 letters followed by 1 integer 
consecutively.\
For other cases, arrange the integers and letters alternatively.

================================================

**Function Call1:**\
function_name(['2', 'r', '6', '7', 'a', '4', 'b', '7', '9', 'c', 'd', '5', '3', '7', '0'])

**Sample Output1:**\
['2', '6', 'r', '7', '4', 'a', '7', '9', 'b', '5', '3', 'c', '7', '0', 'd']

**Explanation1:**\
Since there are 10 integers and 5 letters, the list has been arranged 
according to condition 1.

================================================

**Function Call2:**\
function_name(['r', 'g', '3', 'u', 's', 'f', '8', '6', 's', 'a', 'f', 'i'])

**Sample Output2:**\
['r', 'g', 'u', '3', 's', 'f', 's', '8', 'a', 'f', 'i', '6']

**Explanation2:**\
Since there are 3 integers and 9 letters, the list has been arranged 
according to condition 2.

================================================

**Function Call3:**\
function_name(['2', '6', 't', '5', 'a', 'd', 's', 'f', '7', 'i', 'j', '9', 'a', '4', 'b'])

**Sample Output3:**\
['2', 't', '6', 'a', '5', 'd', '7', 's', '9', 'f', '4', 'i', 'j', 'a', 'b']

**Explanation3:**\
Since there are 6 integers and 9 letters, the list has been arranged 
according to condition 3. The extra letters at the end are left as it was.